boot.o: boot.S multiboot.h x86_desc.h types.h
exception.o: exception.S exception.h
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h
lib.o: lib.c lib.h types.h
phandler.o: phandler.c phandler.h types.h exception.h lib.h x86_desc.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
